name: Deploy MkDocs til GitHub Pages

on:
  push:
    branches:
      - main
  # Tillader manuel aktivering af workflowet fra Actions tab
  workflow_dispatch:

permissions:
  contents: write  # Nødvendigt for at pushe til gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs mkdocs-material

    - name: Deploy to GitHub Pages
      run: mkdocs gh-deploy --force